version: "3"
services:
  provider:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./:/app
    networks:
      - shared
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      - REGISTER_API_URL=http://register:9020
    restart: unless-stopped

networks:
  shared:
    name: shared
    external: true
